auth_path: /user/login
destination_path: /admin/content
deny_message: ''
excluded_403: true
excluded_404: true
excluded_paths: /user/login
_core:
  default_config_hash: GVTXNvHCoxb7wi72IdC2OY5TRiPZNdHACAS8-Isl-EE
